name: First Cron Job

       # Controls when the workflow will run
on: push

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Checkout repo1
        uses: actions/checkout@v3
        with:
          repository: "pavlejacovicHTEC/Bash_Tasks_Snippets"
          path: ./test-path
  
      - name: Checkout repo2
        uses: actions/checkout@v3
        with:
          repository: "pavlejacovicHTEC/Python_tasks"
          path: ./test-path
  
