name: docker-container-data-processing

on: [push]

env:
  LOG_FILES_LOCATION: "/var/log"
  ALTERNATIVES_LOG: "/var/log/alternatives.log"
  ACCESS_LOG: "/var/log/nginx/access.log"
  ERROR_LOG: "/var/log/nginx/error.log"

jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      
      - name: checkout this repo
        uses: actions/checkout@v3
        
      - name: change directory to log file
        run: |
         cd ${{ env.LOG_FILES_LOCATION }}/
         ls
    
        
        
