name: docker-container-data-processing

on: [push]

env:
  LOG_FILES_LOCATION: "/var/log"
  TEST_LOG: "/var/log/nginx/test.log"
  ACCESS_LOG: "/var/log/nginx/access.log"
  ERROR_LOG: "/var/log/nginx/error.log"
  NGINX_CONTAINER_NAME: "webhost"

jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      
      - name: checkout this repo
        uses: actions/checkout@v3
        
      - name: create docker nginx container if it doesnt exist
        run: |
          if [ $( docker ps -a -f name=${{ env.NGINX_CONTAINER_NAME }} | wc -l ) -eq 2 ]; then
            echo "nginx container exists"
          else
            docker container run --publish 8080:80 --name webhost -d nginx
          fi
      
      - name: run docker nginx container if it is not running
        run: |
          if [ "$( docker container inspect -f '{{.State.Status}}' ${{ env.NGINX_CONTAINER_NAME }} )" == "running" ]; then
            echo "nginx container already running"
          else
            docker container start ${{ env.NGINX_CONTAINER_NAME }}
          fi
        
      - name: list all log files
        run: |
         docker exec -i ${{ env.NGINX_CONTAINER_NAME }} ls ${{ env.LOG_FILES_LOCATION }}

      - name: extract test log
        run: |
         docker exec -i ${{ env.NGINX_CONTAINER_NAME }} cat ${{ env.TEST_LOG }} > output.log
         
      - name: upload log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
        
        
