name: docker-container-data-processing

on: [push]

env:
  LOG_FILES_LOCATION: "/var/log"
  TEST_LOG: "test.log"
  ACCESS_LOG: "/var/log/nginx/access.log"
  ERROR_LOG: "/var/log/nginx/error.log"
  NGINX_CONTAINER_NAME: "webhost"

jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      
      - name: checkout this repo
        uses: actions/checkout@v3
        
      - name: create docker nginx container if it doesnt exist
        run: |
          if [ $( docker ps -a -f name=${{ env.NGINX_CONTAINER_NAME }} | wc -l ) -eq 2 ]; then
            echo "nginx container exists"
          else
            docker container run --publish 8080:80 --name webhost -d nginx
          fi
      
      - name: run docker nginx container if it is not running
        run: |
          if [ "$( docker container inspect -f '{{.State.Status}}' ${{ env.NGINX_CONTAINER_NAME }} )" == "running" ]; then
            echo "nginx container already running"
          else
            docker container start ${{ env.NGINX_CONTAINER_NAME }}
          fi
        
      - name: extract wanted logs
        run: |
         docker exec -it 4c587050b5e5 bash
         cd ${{ env.LOG_FILES_LOCATION }}/
         ls
    
        
        
