name: docker-container-data-processing

on: [push]

env:
  ALTERNATIVES_LOG_LOCATION: "/var/log/alternatives.log"
  ACCESS_LOG_LOCATION: "/var/log/nginx/access.log"
  ERROR_LOG_LOCATION: "/var/log/nginx/error.log"

jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      
      - name: checkout this repo
        uses: actions/checkout@v3
      
      - name: update packages
        run: apt-get update
        
      - name: change directory to log file
        run: cd ${{ env.ALTERNATIVES_LOG_LOCATION }}
        
      - name: test
        run: ls
